# Generated by Django 4.1.7 on 2023-03-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentinformation',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentsinterests',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='studentsinterests',
            name='student',
        ),
        migrations.RemoveField(
            model_name='techstack',
            name='project',
        ),
        migrations.RemoveField(
            model_name='techstack',
            name='tech_requirements',
        ),
        migrations.DeleteModel(
            name='Applications',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='StudentInformation',
        ),
        migrations.DeleteModel(
            name='StudentsInterests',
        ),
        migrations.DeleteModel(
            name='TechnicalRequirements',
        ),
        migrations.DeleteModel(
            name='TechStack',
        ),
    ]
