# Generated by Django 4.1.7 on 2023-03-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_customer_remove_studentinformation_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalRequirements',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
