# Generated by Django 4.1.7 on 2023-03-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_technicalrequirements_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='technical_requirements',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
            ],
        ),
        migrations.DeleteModel(
            name='TechnicalRequirements',
        ),
    ]
