# Generated by Django 4.1.7 on 2023-03-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_technical_requirements_delete_technicalrequirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technical_requirements',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
