# Generated by Django 4.1.7 on 2023-03-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_technical_requirements_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.CharField(max_length=5000, verbose_name='description')),
                ('project_type', models.CharField(max_length=20, verbose_name='project_type')),
                ('superviser', models.CharField(max_length=100, verbose_name='superviser')),
                ('number_of_students', models.IntegerField(verbose_name='number_of_students')),
                ('submission_deadline', models.DateField(verbose_name='submission_deadline')),
                ('application_deadline', models.DateField(verbose_name='application_deadline')),
                ('application_form', models.CharField(max_length=255, verbose_name='application_form')),
                ('status', models.CharField(max_length=20, verbose_name='status')),
            ],
        ),
    ]
