# Generated by Django 4.1.7 on 2023-03-14 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='requirements_stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_id', to='server.project')),
                ('requirement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_id', to='server.technical_requirements')),
            ],
        ),
    ]
