# Generated by Django 4.1.7 on 2023-03-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_student_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('group', models.CharField(max_length=10, verbose_name='group')),
                ('year', models.IntegerField(verbose_name='year')),
                ('faculty', models.CharField(max_length=255, verbose_name='faculty')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone_number')),
            ],
        ),
    ]
