# Generated by Django 4.1.7 on 2023-03-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_student_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('project_type', models.CharField(max_length=20)),
                ('supervisor', models.CharField(default='', max_length=255)),
                ('number_of_students', models.IntegerField()),
                ('submission_deadline', models.DateField()),
                ('application_deadline', models.DateField()),
                ('application_form', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'student_applications',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='superviser',
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.CharField(default='', max_length=100, verbose_name='supervisor'),
        ),
    ]
