# Generated by Django 4.1.7 on 2023-03-14 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_student_applications_remove_project_superviser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_id', to='server.technical_requirements')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_id', to='server.student')),
            ],
        ),
    ]
