# Generated by Django 4.1.7 on 2023-03-14 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_student_interest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_applications',
        ),
    ]
