# Generated by Django 4.1.7 on 2023-03-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_delete_student_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_applications',
            fields=[
                ('unique_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='unique_id')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('project_type', models.CharField(max_length=20, verbose_name='project_type')),
                ('supervisor', models.CharField(default='', max_length=255, verbose_name='supervisor')),
                ('number_of_students', models.IntegerField(verbose_name='number_of_students')),
                ('submission_deadline', models.DateField(verbose_name='submission_deadline')),
                ('application_deadline', models.DateField(verbose_name='application_deadline')),
                ('application_form', models.CharField(max_length=255, verbose_name='application_form')),
                ('status', models.CharField(max_length=20, verbose_name='status')),
                ('student_id', models.IntegerField(verbose_name='student_id')),
            ],
            options={
                'db_table': 'student_applications',
                'managed': False,
            },
        ),
    ]
