# Generated by Django 4.1.7 on 2023-03-14 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_student_applications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': False},
        ),
    ]
