# Generated by Django 4.1.7 on 2023-03-14 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_alter_application_options_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='application',
            table='application',
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
    ]
