# Generated by Django 4.1.7 on 2023-03-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_project_requirements_student_information_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_id', models.IntegerField(verbose_name='interest_id')),
                ('student_id', models.IntegerField(verbose_name='student_id')),
            ],
            options={
                'db_table': 'student_interests',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='requirements_stack',
            table='requirements_stack',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
        migrations.AlterModelTable(
            name='student_info',
            table='student_info',
        ),
        migrations.AlterModelTable(
            name='student_interests_list',
            table='student_interests_list',
        ),
        migrations.AlterModelTable(
            name='technical_requirements',
            table='technical_requirements',
        ),
        migrations.DeleteModel(
            name='student_interest',
        ),
    ]
